### ISSUE TITLE
Support for Python 3?

### ISSUE THREAD

**Issue by Legomaniac** [concongo/pylacrossapi#1]
Hello @concongo !

I am very interested in using your module in Python 3. In fact, I already got it working with very minimal changes! I am hoping I could convince you to make those changes, and promote them to PyPi.

Line 1 and 2:
`from urllib import request`
`from urllib import parse`

Line 63:
`data = parse.urlencode(params)`

Line 66:
`req = request.Request(self.__url_base + '?' + data, None, headers)`

Line 68:
`req = request.Request(self.__url_base, None, headers)`

Line 70:
`page = request.urlopen(req).read()`

If you don't have the time to make these changes would you be willing to let me make a pull request and attempt to get the changes published to PyPi?

Thank you so much for your time!

Edit: I have made a pull request here -  #2 

@Legomaniac

**Comment by concongo** [comment]
You got it!
