### ISSUE TITLE
Upload most recent changes to PyPi?

### ISSUE THREAD

**Issue by Legomaniac** [concongo/pylacrossapi#4]
Hello concongo,

Thanks for your responsiveness with my pull requests!

I am hoping to use this module with a project that requires it to be available to pip at the time my code is loaded into the platform. 

I see you merged my pull request to get rid of the limit on Python < 3.5, but I don't believe those changes have been uploaded to PyPi so pip is able to install without issue.

Do you have any availability to package the latest changes and upload them to pip to remove the limitation?

Thanks again for your support!

Legomaniac

**Comment by concongo** [comment]
Hello @Legomaniac! Thanks for the interest! I have uploaded the new package to PyPi. Package Ver 0.3
